#!/usr/bin/env bash

cwd=$(pwd)
SERIES_DIR="/media/storage/series/"

case $1 in
    stagger)
        cd $SERIES_DIR || exit 1
        series=$(find -- * -maxdepth 0 -type d | dmenu -i -p "series")
        if [ ! -e "$series" ]; then
            exit 1
        fi
        cd "$series" || exit 1
        season=$(
            find -- * -maxdepth 0 -type d | dmenu -i -p "season"
        )
        if [ ! -e "$season" ]; then
            exit 1
        fi
        cd "$season" || exit 1
        episode=$(
            find -- * -type f | dmenu -i -F -p "episode"
        )
        if [ -e "$episode" ]; then
            ep_no=$(echo "$episode" | grep -Po "(?<=s\d{2}e)(\d{2})(?=.*)")
            mpv . --playlist-start="$ep_no"
        else
            exit 1
        fi
        ;;
    all)
        cd $SERIES_DIR || exit 1
        series=$(find -- * -type f | dmenu -i -F -p "series")
        if [ ! -e "series" ]; then
            mpv "$series"
        else
            exit 1
        fi
        ;;
esac
cd "$cwd" || exit 1
