#!/usr/bin/env bash

cwd=$(pwd)
BOOK_DIR="/media/storage/books"

case $1 in
    stagger)
        cd $BOOK_DIR || exit 1
        subject=$(find -- * -maxdepth 0 -type d | dmenu -i -p "subject")
        if [ ! -e "$subject" ]; then
            exit 1
        fi
        cd "$subject" || exit 1
        #echo "after subject before topic $(pwd)"
        topic=$(
            find -- * -maxdepth 0 -type d | dmenu -i -p "topic"
        )
        if [ ! -e "$topic" ]; then
            exit 1
        fi
        cd "$topic" || exit 1
        #echo "after topic before book $(pwd)"
        books=$(
            find -- * -type f | dmenu -i -F -p "book"
        )
        #echo "after book $books"
        echo "$books is books"
        if [ -e "$books" ]; then
            zathura "$books"
        else
            exit 1
        fi
        ;;
    all)
        cd $BOOK_DIR || exit 1
        books=$(find -- * -type f | dmenu -i -F -p "book")
        if [ -e "$books" ]; then
            zathura "$books"
        else
            exit 1
        fi
        ;;
esac
cd "$cwd" || exit 1
#echo "$books"
