#!/usr/bin/env bash

cwd=$(pwd)
BOOK_DIR="/media/storage/books"
cd $BOOK_DIR || exit 1
subject=$(find ./* -maxdepth 0 -type d | dmenu -i)
echo "after subject before topic $(pwd)"
topic=$(
	cd "$subject" || exit 1
	find ./* -maxdepth 0 -type d | dmenu -i
)
echo "after topic before book $(pwd)"
books=$(
	cd "$topic" || exit 1
	find ./* -type f | dmenu -i
)
echo "after book $(books)"
# tabbed -c -r 2 zathura -e id $books
cd "$cwd" || exit 1
echo "$books"
