#!/usr/bin/env bash

BAR_HEIGHT=18

case $1 in
    "hide")
        polybar-msg cmd hide

        #sleep 0.1
        bspc config top_padding 0
        bspc config bottom_padding 0
        ;;

    "show")
        # Is reversed so it would like the action was undoed.
        bspc config top_padding $BAR_HEIGHT
        bspc config bottom_padding $BAR_HEIGHT

        #sleep 0.1
        polybar-msg cmd show
        ;;
esac
