#! /usr/bin/env bash

BOOK_DIR="/media/storage/books"

CWD=$(pwd)
cd $BOOK_DIR
books=$(find * -type f |
            fzf --header="Choose books." -m)
n_books=$(echo "$books" | wc -l)
if [ ! -z "$books" ]
then
    tabbed -c -r 2 zathura -e id $books & disown
    echo "Opened $n_books books."
    cd $CWD
else
    echo "No books selected."
    cd $CWD
    exit 1
fi
exit 0
