#!/usr/bin/env bash

# colors prefixed with alpha values
# colors for locked windows
: "${LOCKED_NORMAL_BCOLOR:=0xff98971a}"
: "${LOCKED_ACTIVE_BCOLOR:=0xff98971a}"
: "${LOCKED_FOCUSED_BCOLOR:=0xffb8bb26}"
# colors for sticky windows
: "${STICKY_NORMAL_BCOLOR:=0xff458588}"
: "${STICKY_ACTIVE_BCOLOR:=0xff458588}"
: "${STICKY_FOCUSED_BCOLOR:=0xff83af98}"
# colors for marked windows
: "${MARKED_NORMAL_BCOLOR:=0xffd79921}"
: "${MARKED_ACTIVE_BCOLOR:=0xffd79921}"
: "${MARKED_FOCUSED_BCOLOR:=0xfffabd2f}"

while bspc subscribe -c 1 node_focus node_flag > /dev/null; do
    bspc config focused_border_color "$(bspc config focused_border_color)"
    bspc config normal_border_color "$(bspc config normal_border_color)"
    # locked windows
    bspc query -N -n '.locked.!focused.window' | while read -r wid; do
        chwb -c "$LOCKED_NORMAL_BCOLOR" "$wid"
    done
    bspc query -N -n '.locked.active.!focused.window' | while read -r wid; do
        chwb -c "$LOCKED_ACTIVE_BCOLOR" "$wid"
    done
    bspc query -N -n "focused.locked" | while read -r wid; do
        chwb -c "$LOCKED_FOCUSED_BCOLOR" "$wid"
    done
    # stickied windows
    bspc query -N -n '.sticky.!focused.window' | while read -r wid; do
        chwb -c "$STICKY_NORMAL_BCOLOR" "$wid"
    done
    bspc query -N -n '.sticky.active.!focused.window' | while read -r wid; do
        chwb -c "$STICKY_ACTIVE_BCOLOR" "$wid"
    done
    bspc query -N -n "focused.sticky" | while read -r wid; do
        chwb -c "$STICKY_FOCUSED_BCOLOR" "$wid"
    done
    # marked windows
    bspc query -N -n '.marked.!focused.window' | while read -r wid; do
        chwb -c "$MARKED_NORMAL_BCOLOR" "$wid"
    done
    bspc query -N -n '.marked.active.!focused.window' | while read -r wid; do
        chwb -c "$MARKED_ACTIVE_BCOLOR" "$wid"
    done
    bspc query -N -n "focused.marked" | while read -r wid; do
        chwb -c "$MARKED_FOCUSED_BCOLOR" "$wid"
    done
done
