#!/usr/bin/env bash

chosen=$(cut -d ';' -f1 ~/data/emojis | dmenu -i -F -l 30 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	printf "$chosen" | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
