#!/usr/bin/env bash

BORDER_WIDTH=4
BORDER_WIDTH_WITHOUT_GAP=2
GAP=10
GAP_STATE=$HOME/data/state-files/.gap-state

if [ ! -e $GAP_STATE ]; then
    touch $GAP_STATE
    bspc config window_gap 0
    bspc config border_width $BORDER_WIDTH_WITHOUT_GAP
else
    rm $GAP_STATE
    bspc config border_width $BORDER_WIDTH
    bspc config window_gap $GAP
fi
