#!/usr/bin/env bash
monitors=("kitty" "top" "htop" "bashtop" "glances" "vtop" "bottom" "atop" "gotop")
term="kitty"

options="${monitors[0]}"
for monitor in "${monitors[@]:1}";
do
    options+="\n"
    options+="$monitor"
done
selected="$(echo -e "$options" | dmenu -p 'monitors: ' -i)"
if [ $selected ];
then
    if [ "$selected" = "bottom" ];then
        $term btm
    else
        $term $selected
    fi
    exit 0
else
    exit 1
fi
