#!/usr/bin/env bash

files=$(find -maxdepth 1 -type f)
for file in $files; do
    dim=$(identify $file | cut -d " " -f3)
    x=$(echo "$dim" | cut -d "x" -f1)
    y=$(echo "$dim" | cut -d "x" -f2)
    if [[ $y -gt $x ]]; then
        echo "$file"
    fi
done
