#!/usr/bin/env python3

import subprocess
import sys, os


def arg_parser(arguments):
    n_args = len(arguments)
    sub, vid = "", ""
    if arguments[0][-3:] == "srt":
        sub = arguments.pop(0)
        vid = arguments[0]
    else:
        vid = arguments.pop(0)
        sub = arguments[0]
    out = vid.split(".")
    out.insert(-1, "out")
    out = ".".join(out)
    return [vid, sub, out]


ARGS = sys.argv
if len(ARGS) == 1:
    METHOD = "bat"
elif len(ARGS) == 3:
    METHOD = "ind"
elif len(ARGS) == 2 and ARGS[1] in ["-h", "--h", "--help", "-help"]:
    METHOD = "hlp"
else:
    raise Exception("not enough parameters supplied.")


def merger(video, sub, out):
    if video[-3:] in ["mp4", "mkv", "avi"] and sub[-3:] == "srt":
        if out[-3:] in ["mp4", "avi"]:
            out = out.split(".")
            out[-1] = "mp4"
            out = ".".join(out)
            command = f"""ffmpeg -i {video} -f srt -i {sub} -map 0:0 -map 0:1 \
-map 1:0 -c:v copy -c:a copy -c:s mov_text {out}"""
        elif out[-3:] == "mkv":
            command = f"""ffmpeg -i {video} -f srt -i {sub} -map 0:0 -map 0:1 \
-map 1:0 -c:v copy -c:a copy -c:s srt {out}"""
        else:
            raise ValueError("Output file format invalid. Use .mp4 or .mkv")
    else:
        raise ValueError("Input file format is invalid. Use .mp4, .mkv or .avi")
    return command


def batch_merge(vids, subs):
    if len(vids) == len(subs):
        n_files = len(vids)
        vids.sort()
        subs.sort()
        for _ in range(n_files):
            out_file = vids[_].split(".")
            out_file.insert(-1, "out")
            out_file = ".".join(out_file)
            command = merger(vids[_], subs[_], out_file)
            print(f"combining {vids[_]}")
            os.system(command + ">/dev/null 2>&1")
        print(f"done merging {n_files} videos.")
    else:
        raise ValueError("Mismatch between number of videos and subtitles.")


def ind_merge(vid, sub, out):
    command = merger(vid, sub, out)
    print(f"combining {vid}...", end="")
    os.system(command + ">/dev/null 2>&1")
    print("done.")


if METHOD == "bat":
    files = os.listdir()
    vids = [i for i in files if i[-3:] in ["mp4", "mkv", "avi"]]
    subs = [i for i in files if i[-3:] in ["srt"]]
    batch_merge(vids, subs)
elif METHOD == "ind":
    args = sys.argv[1:]
    files = arg_parser(args)
    ind_merge(files[0], files[1], files[2])
elif METHOD == "hlp":
    print("usage: video+sub videofile subfile.")
    print(
        """videofile can be mp4, mkv or avi format, and \
subtitle can be srt format"""
    )
    print(
        """not specifying any arguments will batch-merge all relevant \
files in the current directory"""
    )
