#!/usr/bin/env bash

BAR_HEIGHT=18
GAP=10
BORDER_WIDTH=4
BORDER_WIDTH_THIN=2

GAP_STATE=$HOME/data/state-files/.gap-state
BAR_STATE=$HOME/data/state-files/.bar-state
BOR_STATE=$HOME/data/state-files/.border-state

case $1 in
bar)
	if [ ! -e $BAR_STATE ]; then
		touch $BAR_STATE
		polybar-msg cmd hide
		bspc config top_padding 0
		bspc config bottom_padding 0
	else
		rm $BAR_STATE
		bspc config top_padding $BAR_HEIGHT
		bspc config bottom_padding $BAR_HEIGHT
		polybar-msg cmd show
	fi
	;;
gap)
	if [ ! -e $GAP_STATE ]; then
		touch $GAP_STATE
		bspc config window_gap 0
		bspc config border_width $BORDER_WIDTH_THIN
	else
		rm $GAP_STATE
		bspc config border_width $BORDER_WIDTH
		bspc config window_gap $GAP
	fi
	;;
border)
	if [ ! -e $BOR_STATE ]; then
		touch $BOR_STATE
		bspc config border_width 0
	else
		rm $BOR_STATE
		bspc config border_width $BORDER_WIDTH
	fi
	;;
esac
